home:
    path: /
    defaults: { _controller: AppBundle:Main:index }

login:
    path: /login
    defaults: { _controller: AppBundle:Main:login }

search_users:
    path: /ajax/search-users
    defaults: { _controller: AppBundle:Main:searchUsers }
    
user:
    path: /{name}/comment
    defaults: { _controller: AppBundle:Main:user }

find_comments:
    path: /{user}/comments/find/{git}
    defaults: { _controller: AppBundle:Main:findComments, git: null }

send_comment:
    path: /{user}/comments/send
    defaults: { _controller: AppBundle:Main:sendComment }